{
	"schemaSections": [
		{
			"sectionAforo": "18",
			"sectionDistribution": {
				"row-A": {
					"0": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-1"
					},
					"1": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-2"
					},
					"2": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-3"
					},
					"3": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-4"
					},
					"4": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-5"
					},
					"5": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-6"
					}
				},
				"row-B": {
					"0": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-1"
					},
					"1": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-2"
					},
					"2": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-3"
					},
					"3": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-4"
					},
					"4": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-5"
					},
					"5": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-6"
					}
				},
				"row-C": {
					"0": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-1"
					},
					"1": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-2"
					},
					"2": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-3"
					},
					"3": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-4"
					},
					"4": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-5"
					},
					"5": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-6"
					}
				}
			},
			"sectionDoor": "E",
			"sectionLetter": "AA",
			"sectionName": "PALCO I",
			"sectionNumeration": "1",
			"typeDistribution": "seat",
			"typeSection": "numbered"
		},
		{
			"sectionAforo": "18",
			"sectionDistribution": {
				"row-A": {
					"0": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-1"
					},
					"1": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-2"
					},
					"2": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-3"
					},
					"3": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-4"
					},
					"4": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-5"
					},
					"5": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "A-6"
					}
				},
				"row-B": {
					"0": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-1"
					},
					"1": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-2"
					},
					"2": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-3"
					},
					"3": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-4"
					},
					"4": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-5"
					},
					"5": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "B-6"
					}
				},
				"row-C": {
					"0": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-1"
					},
					"1": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-2"
					},
					"2": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-3"
					},
					"3": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-4"
					},
					"4": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-5"
					},
					"5": {
						"seatCheckboxChecked": true,
						"seatCheckboxDisabled": false,
						"seatLabel": "C-6"
					}
				}
			},
			"sectionDoor": "E",
			"sectionLetter": "AB",
			"sectionName": "VIP I",
			"sectionNumeration": "19",
			"typeDistribution": "seat",
			"typeSection": "numbered"
		},
		{
			"sectionAforo": "90",
			"sectionDoor": "E",
			"sectionLetter": "AC",
			"sectionName": "GENERAL",
			"sectionNumeration": "37",
			"typeDistribution": "standUp",
			"typeSection": "numbered"
		}
	]
}